config/routes.rb
Rails.application.routes.draw do
  resources :images
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'


  resources :registrations do
    collection do
      get :validate_email
    end
  end

  resources :users, only: [:index, :edit, :update, :destroy]

  resources :admins, only: [:index] do
    collection do
      get :all
      get :approved
      get :pending
      get :rejected
    end
  end
  resources :buyers, only: [:index]
  resources :sellers do
    collection do
      get :approved
      get :pending
      get :rejected
    end
  end
  
  resources :products, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :images
    member do
      put :approve
      put :reject
    end
  end

  resources :favourites, only: [:index, :destroy] do
    member do
      post :add
    end
  end
  resources :carts, only: [:index, :destroy] do
    member do
      post :add
    end
  end

  root 'sessions#new'

end

app/views/shared/_admin_navbar.html.erb
<!--Main Navigation-->
<header>

  <nav class="navbar fixed-top navbar-expand-lg navbar-dark primary-color scrolling-navbar">
    <div class="container">
      <a class="navbar-brand" href="#"><strong>Admin</strong></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to 'All', all_admins_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Approved', approved_admins_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Pending', pending_admins_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Rejected', rejected_admins_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Users', users_path, class: "nav-link" %>
          </li>
        </ul>
        <ul class="navbar-nav nav-flex-icons">
          <li class="nav-item">
            <a class="nav-link"><i class="far fa-user"></i> <%= current_user.first_name %></a>
          </li>
          <li class="nav-item">
            <%= link_to 'Logout', logout_path, method: :delete, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </div>
  </nav>

</header>
<!--Main Navigation-->

app/views/shared/_buyer_navbar.html.erb
<!--Main Navigation-->
<header>

  <nav class="navbar fixed-top navbar-expand-lg navbar-dark primary-color scrolling-navbar">
    <div class="container">
      <a class="navbar-brand" href="#"><strong>Buyer</strong></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to 'All Products', buyers_path, class: "nav-link" %>
          </li>
          <li class="nav-item fav-nav">
            <%- favourites = Favourite.where(user_id: current_user.id) %>
            <%= link_to 'Favourites', favourites_path, class: "nav-link" %> <% if favourites.present? %> <small class="items-counter"><%= favourites.count %></small> <% end %>
          </li>
          <li class="nav-item cart-nav">
            <%- carts = Cart.where(user_id: current_user.id) %>
            <%= link_to "Cart", carts_path, class: "nav-link" %><% if carts.present? %> <small class="items-counter"><%= carts.count %></small> <% end %>
          </li>
        </ul>
        <ul class="navbar-nav nav-flex-icons">
          <li class="nav-item">
            <a class="nav-link"><i class="far fa-user"></i> <%= current_user.first_name %></a>
          </li>
          <li class="nav-item">
            <%= link_to 'Logout', logout_path, method: :delete, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </div>
  </nav>

</header>
<!--Main Navigation-->

app/views/shared/_carts_list.html.erb
<% if carts.present? %>
  <div class="card mb-3">
    <div class="card-body">
      <p class="h4 m-0 text-primary text-center">Total Amount: <%= @total %> </p>
    </div>
  </div>
  <% carts.each do |cart|%>
    <div class="card mb-3">
      <div class="card-body">
        <div class="media">
          <img class="d-flex align-self-center mr-3" src="https://cahsi.utep.edu/wp-content/uploads/kisspng-computer-icons-user-clip-art-user-5abf13db5624e4.1771742215224718993529.png" height="50" alt="Generic placeholder image">
          <div class="media-body my-auto">
            <h4 class="my-0 font-weight-bold"><%= cart.product.user.first_name %></h4>
            <small class="my-0 text-black-50"><%= time_ago_in_words(cart.product.created_at) %> ago</small>
          </div>
          <div class="dropleft">
            <div class="product-actions dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-ellipsis-v"></i>
            </div>
            <div class="dropdown-menu">
              <%= link_to 'Add to Favourites', add_favourite_path(cart.product), class: "dropdown-item", method: :post unless Favourite.where(user_id: current_user.id, product_id: cart.product.id).present? %>
              <%= link_to 'Remove from cart', cart_path(cart), class: "dropdown-item", method: :delete %>
            </div>
          </div>
        </div>
        <div class="product-description">
          <strong class="text-primary">Product Name: </strong><%= cart.product.name %>
          <br>
          <strong class="text-primary">Description: </strong><%= truncate("#{cart.product.description}", :length => 100) %>
          <br>
          <strong class="text-primary">Price: </strong><%= cart.product.price %>$
          <div class="text-center">
            <%= link_to 'View Product', product_path(cart.product) %>
          </div>
          <hr>
          <small class="my-0 text-black-50"> Created at: <%= cart.product.created_at.to_formatted_s(:long) %></small>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <div class="card mb-3">
    <div class="card-body">
      <p class="h1-responsive m-0 text-black-50 text-center">Cart is empty</p>
    </div>
  </div>
<% end %>

app/views/shared/_favourites_list.html.erb
<% if favourites.present? %>
  <% favourites.each do |favourite|%>
    <div class="card mb-3">
      <div class="card-body">
        <div class="media">
          <img class="d-flex align-self-center mr-3" src="https://cahsi.utep.edu/wp-content/uploads/kisspng-computer-icons-user-clip-art-user-5abf13db5624e4.1771742215224718993529.png" height="50" alt="Generic placeholder image">
          <div class="media-body my-auto">
            <h4 class="my-0 font-weight-bold"><%= favourite.product.user.first_name %></h4>
            <small class="my-0 text-black-50"><%= time_ago_in_words(favourite.product.created_at) %> ago</small>
          </div>
          <div class="dropleft">
            <div class="product-actions dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-ellipsis-v"></i>
            </div>
            <div class="dropdown-menu">
              <% if current_user.role == "buyer"%>
                <%= link_to 'Remove from Favourites', favourite_path(favourite), class: "dropdown-item", method: :delete %>
                <%= link_to 'Add to Cart', add_cart_path(favourite.product), class: "dropdown-item", method: :post unless Cart.where(user_id: current_user.id, product_id: favourite.product.id).present? %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="product-description">
          <strong class="text-primary">Product Name: </strong><%= favourite.product.name %>
          <br>
          <strong class="text-primary">Description: </strong><%= truncate("#{favourite.product.description}", :length => 100) %>
          <br>
          <strong class="text-primary">Price: </strong><%= favourite.product.price %>$
          <div class="text-center">
            <%= link_to 'View Product', product_path(favourite.product) %>
          </div>
          <hr>
          <small class="my-0 text-black-50"> Created at: <%= favourite.product.created_at.to_formatted_s(:long) %></small>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <div class="card mb-3">
    <div class="card-body">
      <p class="h1-responsive m-0 text-black-50 text-center">Favourites not found</p>
    </div>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message|%>
  <div class="alert alert-<%= type %> alert-dismissible pl-4 fade show" role="alert">
    <%= message %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_model_messages.html.erb
<% if model.errors.any? %> 
  <ol class="p-0"> 
    <div class="alert alert-danger alert-dismissible pl-4 fade show" role="alert">
      <% model.errors.full_messages.each do |message| %> 
        <li><%= message %></li> 
      <% end %> 
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </ol>
<% end %>

app/views/shared/_products_list.html.erb
<% if products.present? %>
  <% products.each do |product|%>
    <div class="card mb-3">
        <div class="card-body px-5 py-5">
          <div class="media">
            <div class="media-body my-auto">
              <h4 class="my-0 font-weight-bold"><%= product.name %></h4>
              <small class="my-0 text-black-50"><%= time_ago_in_words(product.created_at) %> ago</small>
            </div>
            <div class="dropleft">
              <div class="product-actions dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v"></i>
              </div>
              <div class="dropdown-menu">
                <% if current_user.role == "admin"%>
                  <%= link_to 'Approve', approve_product_path(product), class: "dropdown-item", method: :put if product.status != "approved" %>
                  <%= link_to 'Reject', reject_product_path(product), class: "dropdown-item", method: :put if product.status != "rejected" %>
                <% end %>
                <% if current_user.role == "buyer"%>
                  <%= link_to 'Add to Favourites', add_favourite_path(product), class: "dropdown-item", method: :post unless Favourite.where(user_id: current_user.id, product_id: product.id).present? %>
                  <%= link_to 'Add to Cart', add_cart_path(product), class: "dropdown-item", method: :post unless Cart.where(user_id: current_user.id, product_id: product.id).present? %>
                <% end %>
                <% if current_user.role == "seller"%>
                  <%= link_to 'Edit', edit_product_path(product), class: "dropdown-item" %>
                  <%= link_to 'Delete', product_path(product), class: "dropdown-item", method: :delete %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="product-description">
            <%= product.description %>
            <hr>
            <div class="text-center">
            <%= link_to 'View Product', product_path(product) %>
            </div>
            <hr>
            <small class="my-0 text-black-50"> Created at: <%= product.created_at.to_formatted_s(:long) %></small>
          </div>
        </div>
    </div>
  <% end %>
<% else %>
  <div class="card mb-3">
    <div class="card-body">
      <p class="h1-responsive m-0 text-black-50 text-center">Products not found</p>
    </div>
  </div>
<% end %>

app/views/shared/_seller_navbar.html.erb
<!--Main Navigation-->
<header>

  <nav class="navbar fixed-top navbar-expand-lg navbar-dark primary-color scrolling-navbar">
    <div class="container">
      <a class="navbar-brand" href="#"><strong>Seller</strong></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to 'Approved', approved_sellers_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Pending', pending_sellers_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Rejected', rejected_sellers_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Create Product', new_product_path, class: "nav-link" %>
          </li>
        </ul>
        <ul class="navbar-nav nav-flex-icons">
          <li class="nav-item">
            <a class="nav-link"><i class="far fa-user"></i> <%= current_user.first_name %></a>
          </li>
          <li class="nav-item">
            <%= link_to 'Logout', logout_path, method: :delete, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </div>
  </nav>

</header>
<!--Main Navigation-->