config/routes.rb
Rails.application.routes.draw do
  resources :images
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'


  resources :registrations do
    collection do
      get :validate_email
    end
  end

  resources :users, only: [:index, :edit, :update, :destroy]

  resources :admins, only: [:index] do
    collection do
      get :all
      get :approved
      get :pending
      get :rejected
    end
  end
  resources :buyers, only: [:index]
  resources :sellers do
    collection do
      get :approved
      get :pending
      get :rejected
    end
  end
  
  resources :products, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :images
    member do
      put :approve
      put :reject
    end
  end

  resources :favourites, only: [:index, :destroy] do
    member do
      post :add
    end
  end
  resources :carts, only: [:index, :destroy] do
    member do
      post :add
    end
  end

  root 'sessions#new'

end

app/views/forms/_product.html.erb
<div class="product jumbotron px-3 py-4">
  <p class="h3 my-4 text-center">Product Details</p>

  <%= form_with(model: @product, url: products_path, class: 'mx-lg-5', local: true) do |f|%>

    <div class="md-form mt-0">
      <%= f.text_field :name, class: 'form-control', required: true %>
      <%= f.label :name %>
    </div>

    <div class="md-form">
      <%= f.number_field :price, class: 'form-control', min:0, required: true %>
      <%= f.label :price %>
    </div>

    <div class="md-form">
      <%= f.text_area :description, rows: 5, class: 'md-textarea form-control', required: true %>
      <%= f.label :description %>
    </div>

    <%= f.fields_for :images do |image| %>
      <div class="custom-file mb-2">
        <%= image.file_field :picture, class: 'custom-file-input' %>
        <%= image.label :picture, "Picture #{image.index+1}", class: "custom-file-label" %>
      </div>
    <% end %>
    
    <div class="text-center">
      <%= f.submit "Create Product", class: 'btn btn-primary'%>
    </div>
  <% end %>
  
  <%= render "shared/model_messages", model: @product %>

</div>
<!-- News jumbotron -->